# Generated by Django 5.0.6 on 2024-10-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="email",
            field=models.EmailField(
                default="example@example.com", max_length=254, unique=True
            ),
        ),
    ]
